<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Safwans-MacBook-Air.local" failures="1" tests="2" name="com.zee.testcases.VerifURL" time="0.129" errors="0" timestamp="2023-08-15T02:28:54 IST" skipped="1">
  <testcase classname="com.zee.testcases.VerifURL" name="titleURL" time="0.129">
    <failure message="expected [Protractor practice website - Banking App] but found [Protractor practice website - Banking App/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Protractor practice website - Banking App] but found [Protractor practice website - Banking App/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.zee.testcases.VerifURL.titleURL(VerifURL.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
    <system-out>
      <![CDATA[capturing screenshots
<a target="_blank" href="http://localhost:8000/error.png
">View Screenshot</a>
<br>
<a target="_blank" href="http://localhost:8000/error.png
"><img src="http://localhost:8000/error.png
" height=200 width = 200></img></a>]]>
    </system-out>
  </testcase> <!-- titleURL -->
  <testcase classname="com.zee.testcases.VerifURL" name="CheckButton">
    <skipped/>
  </testcase> <!-- CheckButton -->
  <system-out>
    <![CDATA[URl launch successfully
capturing screenshots
<a target="_blank" href="http://localhost:8000/error.png
">View Screenshot</a>
<br>
<a target="_blank" href="http://localhost:8000/error.png
"><img src="http://localhost:8000/error.png
" height=200 width = 200></img></a>]]>
  </system-out>
</testsuite> <!-- com.zee.testcases.VerifURL -->
